server:
  port: 8077
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: loginServiceRoute
          predicates:
            - Path=/loginService/**
          uri: lb://login-service/
        - id: policyOwnedApp
          predicates:
            - Path=/policyOwnedApp/**
          uri: lb://policy-owned-service/
        - id: policyApp
          predicates:
            - Path=/policyApp/**
          uri: lb://policy-service/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
